#!/usr/bin/env bun

import { createHash } from "crypto"
import path from "path"
import { TextureUtils } from "@opentui/core/3d"

const root = path.join(import.meta.dir, "..")
const assetPath = path.join(root, "src/cli/cmd/tui/component/assets/bunny-reference.png")
const outPath = path.join(root, "src/cli/cmd/tui/component/bunny-grid.ts")
const target = Number(process.argv[2] ?? "32")

if (!Number.isInteger(target) || target < 8 || target > 128) {
  throw new Error(`Target grid size must be an integer between 8 and 128, received: ${process.argv[2]}`)
}

const texture = await TextureUtils.fromFile(assetPath)
if (!texture) {
  throw new Error(`Could not decode reference image at ${assetPath}`)
}

const image = texture.image as { data: Uint8Array; width: number; height: number }
const rows = Array.from({ length: target }, (_, y) => {
  return Array.from({ length: target }, (_, x) => {
    const sx = Math.min(image.width - 1, Math.floor(((x + 0.5) / target) * image.width))
    const sy = Math.min(image.height - 1, Math.floor(((y + 0.5) / target) * image.height))
    const i = (sy * image.width + sx) * 4
    const r = image.data[i] ?? 0
    const g = image.data[i + 1] ?? 0
    const b = image.data[i + 2] ?? 0
    const a = image.data[i + 3] ?? 0
    const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
    return a > 20 && lum > 140 ? "w" : "."
  }).join("")
})

const checksum = createHash("sha256").update(rows.join("\n")).digest("hex")

const content = `// Generated by script/generate-bunny-grid.ts from component/assets/bunny-reference.png\n// checksum: ${checksum}\n\nexport const bunnyGrid = {\n  width: ${target},\n  height: ${target},\n  checksum: "${checksum}",\n  rows: [\n${rows.map((row) => `    \"${row}\"`).join(",\n")}\n  ],\n} as const\n`

await Bun.write(outPath, content)
console.log(`Generated ${path.relative(root, outPath)} from ${path.relative(root, assetPath)} (${target}x${target})`)
